# Backend containers 
webserver:
    image: nginx:latest
    ports:
        - "8001:80"
    volumes:
        - ./webserver/webserver.conf:/etc/nginx/conf.d/default.conf
        - ./code:/code
    links:
        - php

php:
    image: php:8.0.0-fpm
    volumes:
        - ./code:/code
    links:
        - database

database:
  image: mariadb:latest
  restart: always
  environment: 
    MYSQL_ROOT_PASSWORD: MrBean!


# Frontend containers