export default {
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
    SET_START_DATE: "SET_START_DATE",
    SET_END_DATE: "SET_END_DATE",
    INCREASE_GUEST_COUNTER: "INCREASE_GUEST_COUNTER",
    DECREASE_GUEST_COUNTER: "DECREASE_GUEST_COUNTER",
    SET_GUEST_COUNTER: "SET_GUEST_COUNTER"
};